ceiling_material: null
floor_material: null
floor_physics: null
goal: null
keyword_objects: null
last_step: null
num_random_interactable_objects: null
performer_start_position: null
performer_start_rotation: null
random_structural_objects: null
room_dimensions: null
room_shape: null
specific_interactable_objects: null
structural_platforms:
  num: 0
structural_ramps:
  num: 0
structural_walls:
  num: 0
passive_scene: false
freezes: null
teleports: null
wall_back_material: null
wall_front_material: null
wall_left_material: null
wall_right_material: null
